[2025-04-21T22:09:26.936-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-21T22:09:27.036-0300] {taskinstance.py:2604} INFO - Dependencies not met for <TaskInstance: integracao_api.integracao_api manual__2025-04-22T00:27:04.872995+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2025-04-21T22:09:27.037-0300] {local_task_job_runner.py:166} INFO - Task is not able to be run
