[2025-04-21T20:14:11.421-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-21T20:14:11.513-0300] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: integracao_api.integracao_api manual__2025-04-21T23:14:01.031265+00:00 [queued]>
[2025-04-21T20:14:11.521-0300] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: integracao_api.integracao_api manual__2025-04-21T23:14:01.031265+00:00 [queued]>
[2025-04-21T20:14:11.521-0300] {taskinstance.py:2867} INFO - Starting attempt 1 of 3
[2025-04-21T20:14:11.544-0300] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): integracao_api> on 2025-04-21 23:14:01.031265+00:00
[2025-04-21T20:14:11.558-0300] {standard_task_runner.py:72} INFO - Started process 11806 to run task
[2025-04-21T20:14:11.567-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'integracao_api', 'integracao_api', 'manual__2025-04-21T23:14:01.031265+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/dag_integration.py', '--cfg-path', '/tmp/tmpiwqcraxx']
[2025-04-21T20:14:11.571-0300] {standard_task_runner.py:105} INFO - Job 52: Subtask integracao_api
[2025-04-21T20:14:11.664-0300] {task_command.py:467} INFO - Running <TaskInstance: integracao_api.integracao_api manual__2025-04-21T23:14:01.031265+00:00 [running]> on host jonathan-brito
[2025-04-21T20:14:11.742-0300] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_team' AIRFLOW_CTX_DAG_ID='integracao_api' AIRFLOW_CTX_TASK_ID='integracao_api' AIRFLOW_CTX_EXECUTION_DATE='2025-04-21T23:14:01.031265+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-21T23:14:01.031265+00:00'
[2025-04-21T20:14:11.743-0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-21T20:14:11.743-0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-21T20:14:11.744-0300] {logging_mixin.py:190} INFO - Current task name:integracao_api state:running start_date:2025-04-21 23:14:11.513563+00:00
[2025-04-21T20:14:11.744-0300] {logging_mixin.py:190} INFO - Dag name:integracao_api and current dag run status:running
[2025-04-21T20:14:11.744-0300] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-21T20:15:58.501-0300] {logging_mixin.py:190} INFO - Erro no chunk 0: 500 Server Error: Internal Server Error for url: http://localhost:8000/integration/
[2025-04-21T20:15:58.502-0300] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/dags/dag_integration.py", line 79, in integra_api
    response.raise_for_status()  # Verifica erros HTTP
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:8000/integration/
[2025-04-21T20:15:58.514-0300] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-21T20:15:58.514-0300] {logging_mixin.py:190} INFO - Task start:2025-04-21 23:14:11.513563+00:00 end:2025-04-21 23:15:58.513742+00:00 duration:107.000179
[2025-04-21T20:15:58.515-0300] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): integracao_api> dag:<DAG: integracao_api> dagrun:<DagRun integracao_api @ 2025-04-21 23:14:01.031265+00:00: manual__2025-04-21T23:14:01.031265+00:00, state:running, queued_at: 2025-04-21 23:14:01.072717+00:00. externally triggered: True>
[2025-04-21T20:15:58.515-0300] {logging_mixin.py:190} INFO - Failure caused by 500 Server Error: Internal Server Error for url: http://localhost:8000/integration/
[2025-04-21T20:15:58.515-0300] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=integracao_api, task_id=integracao_api, run_id=manual__2025-04-21T23:14:01.031265+00:00, execution_date=20250421T231401, start_date=20250421T231411, end_date=20250421T231558
[2025-04-21T20:15:58.548-0300] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-21T20:15:58.549-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 52 for task integracao_api (500 Server Error: Internal Server Error for url: http://localhost:8000/integration/; 11806)
Traceback (most recent call last):
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/dags/dag_integration.py", line 79, in integra_api
    response.raise_for_status()  # Verifica erros HTTP
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:8000/integration/
[2025-04-21T20:15:58.595-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-21T20:15:58.609-0300] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-21T20:15:58.610-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
